### ISSUE TITLE
what does "Add your bundle Id and com.ibm.mobilefirstplatform.clientsdk.android.push" means?

### ISSUE THREAD

**Issue by solidw** [ibm-bluemix-mobile-services/bms-push-react-native#20]
Hi. I'm trying to use this library for my react-native project.

In the README.md, there is three steps for Android FCM.
![image](https://user-images.githubusercontent.com/33471826/89197403-9c517580-d5e6-11ea-9d0d-18710e5084a6.png)

Number 2 and 3 are similar as firebase-messaging but number 1 has "Add your `bundle Id` and `com.ibm.mobilefirstplatform.clientsdk.android.push`"

Is it means make firebase project named my bundle id like `ex) com.myapp.someapp` and `com.ibm.mobilefirstplatform.clientsdk.android.push` both?

Or just add `com.ibm.mobilefirstplatform.clientsdk.android.push` to dependencies in android/build.gradle ?

Thank you for reading. Have a nice day!

**Comment by AnanthaKrish** [comment]
@solidw Hi, add your app bundleId and `com.ibm.mobilefirstplatform.clientsdk.android.push` inside your Firebase project . 

 
<img width="1236" alt="Screenshot 2020-08-04 at 11 00 41 AM" src="https://user-images.githubusercontent.com/16939018/89256493-dc921180-d641-11ea-926d-b4058a7d3ea2.png">

**Comment by solidw** [comment]
Thank you for helping!

I'll notice is it working or not after add app named `com.ibm.mobilefirestplatform.clientsdk.android.push` and My app bundleID

**Comment by solidw** [comment]
It works. Thank you :)
