### ISSUE TITLE
Podspec missing summary and homepage variables

### ISSUE THREAD

**Issue by xiangmin2587** [ibm-bluemix-mobile-services/bms-push-react-native#9]
When I add the node_module in package.json:
"react": "16.8.6",
 "react-dom": "^16.10.2",
"react-native": "0.60.5",
"bmd-push-react-native": "^1.1.0"

then I run the pod install command, I will meet below error:
➜  ios git:(master) ✗ pod install
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18/rbconfig.rb:215: warning: Insecure world writable dir /Users/maggie/Downloads/software in PATH, mode 040777
Ignoring eventmachine-1.2.7 because its extensions are not built.  Try: gem pristine eventmachine --version 1.2.7
Ignoring ffi-1.9.25 because its extensions are not built.  Try: gem pristine ffi --version 1.9.25
Ignoring http_parser.rb-0.6.0 because its extensions are not built.  Try: gem pristine http_parser.rb --version 0.6.0
Detected React Native module pods for RNBmdPushReact, RNGestureHandler, RNReanimated, RNScreens, and RNVectorIcons
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `RNBmdPushReact` from `../node_modules/bmd-push-react-native/ios`
[!] The `RNBmdPushReact` pod failed to validate due to 1 error:
    - ERROR | attributes: Missing required attribute `homepage`.
    - WARN  | source: The version should be included in the Git tag.
    - WARN  | description: The description is equal to the summary.

**Comment by xiangmin2587** [comment]
When I add the homepage in podspec file, the issue will disappeared

**Comment by AnanthaKrish** [comment]
@xiangmin2587 Hi, I have updated the plugin. Please use the version 1.2.0
